# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-19 03:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('when', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
