# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-19 07:34
from __future__ import unicode_literals

import app.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_opinion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Side',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Topic')),
            ],
            bases=(app.models.StrMixin, models.Model),
        ),
        migrations.RemoveField(
            model_name='opinion',
            name='topic',
        ),
        migrations.AddField(
            model_name='opinion',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='opinion',
            name='side',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app.Side'),
            preserve_default=False,
        ),
    ]
