# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-19 17:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_opinion_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opinion',
            name='content',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
