# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-19 19:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20161120_0311'),
    ]

    operations = [
        migrations.AddField(
            model_name='opinion',
            name='valid',
            field=models.BooleanField(default=False),
        ),
    ]
